FROM python:3.12-slim

WORKDIR /app

COPY data_platform/python/requirements.txt /app/data_platform/python/requirements.txt
RUN pip install --no-cache-dir -r /app/data_platform/python/requirements.txt

COPY data_platform /app/data_platform

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONPATH=/app
